import Navbar from "@/components/Navbar";
import { Metadata } from "next";
import { Manrope } from "next/font/google";
import React, { FC } from "react";
import "../../globals.css";
import localFont from "next/font/local";
import { TRPCReactProvider } from "../../../trpc/client";

const manrope = Manrope({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// Adding Helvetica Neue from public folder as secondary font
const helveticaNeue = localFont({
  src: [
    {
      path: "../../../fonts/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../fonts/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App with some ci/cd flavor",
  description: "Generated by create next app",
};

interface HomeLayoutProps {
  children: React.ReactNode;
}

const HomeLayout: FC<HomeLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${helveticaNeue.variable} antialiased`}
      >
        <TRPCReactProvider>
          <div>
            <Navbar /> {children}
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
};

export default HomeLayout;
