import Navbar from "@/components/Navbar";
import { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import React, { FC } from "react";
import "../../globals.css";

const dmSans = DM_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App with some ci/cd flavor",
  description: "Generated by create next app",
};

interface HomeLayoutProps {
  children: React.ReactNode;
}

const HomeLayout: FC<HomeLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <div>
          <Navbar /> {children}
        </div>
      </body>
    </html>
  );
};

export default HomeLayout;
