import Navbar from "@/components/Navbar";
import StoreInitializer from "@/components/StoreInitializer";
import { Metadata } from "next";
import { Manrope } from "next/font/google";
import React, { FC } from "react";
import "../../globals.css";
import localFont from "next/font/local";

const manrope = Manrope({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// Adding Helvetica Neue from public folder as secondary font
const helveticaNeue = localFont({
  src: [
    {
      path: "../../../fonts/HelveticaNeueRoman.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../../fonts/HelveticaNeueMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../../fonts/HelveticaNeueBold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica-secondary",
});

export const metadata: Metadata = {
  title: "Create Next App with some ci/cd flavor",
  description: "Generated by create next app",
};

interface HomeLayoutProps {
  children: React.ReactNode;
}

const HomeLayout: FC<HomeLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${helveticaNeue.variable} antialiased`}
      >
        {/* Initialize stores on client-side */}
        <StoreInitializer />

        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <footer className="bg-muted mt-auto py-8">
            <div className="container mx-auto text-center text-muted-foreground">
              <p>
                © {new Date().getFullYear()} Your Store. All rights reserved.
              </p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
};

export default HomeLayout;
