name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio
      - name: Checkout del código
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23'
          cache: 'npm'

      # 3. Instala las dependencias
      - name: Instalar dependencias
        run: npm install

      # 4. Ejecuta las pruebas
      - name: Ejecutar pruebas
        run: npm test

      # 5. Construye la aplicación
      - name: Construir la aplicación
        run: npm run build

      # # 6. (Opcional) Despliegue: Por ejemplo, usando Vercel CLI
      # - name: Desplegar en Vercel
      #   run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      #   env:
      #     VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      #     VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
